//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolCensusApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licensee
    {
        public int Licensees_id { get; set; }
        public string SurveyID { get; set; }
        public string Entity { get; set; }
        public string Section { get; set; }
        public string PsspPhase { get; set; }
        public string LicenseeType { get; set; }
        public string LicenseeSubType { get; set; }
        public string NameOfLicenseeOrganization { get; set; }
        public Nullable<System.DateTime> DateOfPsspLicenceIssue { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<decimal> LandlinePhoneNoOfLicensee { get; set; }
        public string LicenseePostalAddress { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Entity Entity1 { get; set; }
        public virtual LicenseeSub LicenseeSub { get; set; }
        public virtual LicenseeType LicenseeType1 { get; set; }
        public virtual Section Section1 { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
