//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolCensusApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolDBEntities : DbContext
    {
        public SchoolDBEntities()
            : base("name=SchoolDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessToSchool> AccessToSchools { get; set; }
        public virtual DbSet<AlternativeSource> AlternativeSources { get; set; }
        public virtual DbSet<AreaCovered> AreaCovereds { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<BoundryWall> BoundryWalls { get; set; }
        public virtual DbSet<BuildingCondition> BuildingConditions { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassMedium> ClassMediums { get; set; }
        public virtual DbSet<Cleanliness> Cleanlinesses { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<ConstructionType> ConstructionTypes { get; set; }
        public virtual DbSet<Council> Councils { get; set; }
        public virtual DbSet<CurrentStatu> CurrentStatus { get; set; }
        public virtual DbSet<Date> Dates { get; set; }
        public virtual DbSet<Electricity> Electricities { get; set; }
        public virtual DbSet<EmergencyContact> EmergencyContacts { get; set; }
        public virtual DbSet<EMI> EMIS { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<GroundSurrounding> GroundSurroundings { get; set; }
        public virtual DbSet<HandoverAfterward> HandoverAfterwards { get; set; }
        public virtual DbSet<HardArea> HardAreas { get; set; }
        public virtual DbSet<Hygiene> Hygienes { get; set; }
        public virtual DbSet<InfraClass> InfraClasses { get; set; }
        public virtual DbSet<InfraOffice> InfraOffices { get; set; }
        public virtual DbSet<InfraSpec> InfraSpecs { get; set; }
        public virtual DbSet<InfraStructure> InfraStructures { get; set; }
        public virtual DbSet<Institutions1Km> Institutions1Km { get; set; }
        public virtual DbSet<KeyPerson> KeyPersons { get; set; }
        public virtual DbSet<KeyPerson1> KeyPersons1 { get; set; }
        public virtual DbSet<Lab> Labs { get; set; }
        public virtual DbSet<Licensee> Licensees { get; set; }
        public virtual DbSet<LicenseeSub> LicenseeSubs { get; set; }
        public virtual DbSet<LicenseeType> LicenseeTypes { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationRoad> LocationRoads { get; set; }
        public virtual DbSet<Medium> Media { get; set; }
        public virtual DbSet<NearBy> NearBys { get; set; }
        public virtual DbSet<OwnedBy> OwnedBies { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<PopulationType> PopulationTypes { get; set; }
        public virtual DbSet<PresentStudent> PresentStudents { get; set; }
        public virtual DbSet<ReasonClosed> ReasonCloseds { get; set; }
        public virtual DbSet<ReasonDisconnect> ReasonDisconnects { get; set; }
        public virtual DbSet<Reconciliation> Reconciliations { get; set; }
        public virtual DbSet<Record> Records { get; set; }
        public virtual DbSet<RecordType> RecordTypes { get; set; }
        public virtual DbSet<RegisteredStudent> RegisteredStudents { get; set; }
        public virtual DbSet<RoomMapping> RoomMappings { get; set; }
        public virtual DbSet<RoomNo> RoomNoes { get; set; }
        public virtual DbSet<RoomType> RoomTypes { get; set; }
        public virtual DbSet<SchoolAccess> SchoolAccesses { get; set; }
        public virtual DbSet<SchoolAddress> SchoolAddresses { get; set; }
        public virtual DbSet<SchoolLevel> SchoolLevels { get; set; }
        public virtual DbSet<SchoolLocated> SchoolLocateds { get; set; }
        public virtual DbSet<SchoolShift> SchoolShifts { get; set; }
        public virtual DbSet<SchoolSpec> SchoolSpecs { get; set; }
        public virtual DbSet<SchoolStatu> SchoolStatus { get; set; }
        public virtual DbSet<SchoolStatus> SchoolStatuses { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Section1> Sections1 { get; set; }
        public virtual DbSet<SpecialFacility> SpecialFacilities { get; set; }
        public virtual DbSet<StudentAge> StudentAges { get; set; }
        public virtual DbSet<StudentCleanliness> StudentCleanlinesses { get; set; }
        public virtual DbSet<StudentGender> StudentGenders { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
        public virtual DbSet<Surveyor> Surveyors { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TeacherClass> TeacherClasses { get; set; }
        public virtual DbSet<TeacherCode> TeacherCodes { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<TeachersCleanliness> TeachersCleanlinesses { get; set; }
        public virtual DbSet<TeachersComing> TeachersComings { get; set; }
        public virtual DbSet<TeachersSchoolAccess> TeachersSchoolAccesses { get; set; }
        public virtual DbSet<ToiletFacility> ToiletFacilities { get; set; }
        public virtual DbSet<ToiletFunc> ToiletFuncs { get; set; }
        public virtual DbSet<Toilet> Toilets { get; set; }
        public virtual DbSet<UomArea> UomAreas { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Wall> Walls { get; set; }
        public virtual DbSet<Water> Waters { get; set; }
        public virtual DbSet<WaterSource> WaterSources { get; set; }
        public virtual DbSet<WaterSource1> WaterSources1 { get; set; }
    }
}
