//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolCensusApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredStudent
    {
        public int RegisteredStudents_id { get; set; }
        public string SurveyID { get; set; }
        public string Entity { get; set; }
        public string Section { get; set; }
        public string Class { get; set; }
        public string StudentGender { get; set; }
        public Nullable<int> StudentAge { get; set; }
        public string Medium { get; set; }
        public Nullable<int> TotalNoOfStudentRegistered { get; set; }
        public Nullable<int> InclusiveNoOfStudentRegistered { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Class Class1 { get; set; }
        public virtual ClassMedium ClassMedium { get; set; }
        public virtual Entity Entity1 { get; set; }
        public virtual Section Section1 { get; set; }
        public virtual StudentAge StudentAge1 { get; set; }
        public virtual StudentGender StudentGender1 { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
