//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolCensusApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolAddress
    {
        public int SchoolAddress_id { get; set; }
        public string SurveyID { get; set; }
        public string Entity { get; set; }
        public string Section { get; set; }
        public string Disctrict { get; set; }
        public string Tehsil { get; set; }
        public string Markz { get; set; }
        public string Moza { get; set; }
        public string NA { get; set; }
        public string PP { get; set; }
        public string SchoolPostalAddress { get; set; }
        public Nullable<decimal> LandlinePhonNumber { get; set; }
        public string SchoolPostOffice { get; set; }
        public string LandmarkNearSchool { get; set; }
        public string UnionCouncilNumber { get; set; }
        public string UnionCouncilName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
    
        public virtual Entity Entity1 { get; set; }
        public virtual Section Section1 { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
