//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolCensusApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolAccess
    {
        public int SchoolAccesses_id { get; set; }
        public string SurveyID { get; set; }
        public string Entity { get; set; }
        public string Section { get; set; }
        public string Location { get; set; }
        public Nullable<int> NoOfHouseholdsWithin1KmRadius { get; set; }
        public string LocationRoad { get; set; }
        public string PopulationType { get; set; }
        public string SchoolLocated { get; set; }
        public string AccessToSchool { get; set; }
        public string IsSchoolLocatedInHardAreas { get; set; }
        public Nullable<decimal> DistanceFromTehsilHeadQuarter { get; set; }
        public string LicenseeProfessionOtherThenPsspSchools { get; set; }
        public string LicenseeBelongsFromSameAreaWhereSchoolIsLocated { get; set; }
        public Nullable<decimal> DistanceFromSchoolToLicenseeResidence { get; set; }
        public Nullable<int> HowManyDaysLicenseeAttendThePsspSchoolInAWeek { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual AccessToSchool AccessToSchool1 { get; set; }
        public virtual Entity Entity1 { get; set; }
        public virtual HardArea HardArea { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual LocationRoad LocationRoad1 { get; set; }
        public virtual PopulationType PopulationType1 { get; set; }
        public virtual SchoolLocated SchoolLocated1 { get; set; }
        public virtual Section Section1 { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
