//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolCensusApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolStatus
    {
        public int SchoolStatuses_id { get; set; }
        public string SurveyID { get; set; }
        public string Entity { get; set; }
        public string Section { get; set; }
        public string CurrentStatus { get; set; }
        public string SchoolStatus1 { get; set; }
        public string ReasonIfClosed { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string BuildingUnderIllegalOccupation { get; set; }
    
        public virtual CurrentStatu CurrentStatu { get; set; }
        public virtual Entity Entity1 { get; set; }
        public virtual ReasonClosed ReasonClosed { get; set; }
        public virtual SchoolStatu SchoolStatu { get; set; }
        public virtual Section Section1 { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
