//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolCensusApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int Teachers_id { get; set; }
        public string SurveyID { get; set; }
        public string Entity { get; set; }
        public string Section { get; set; }
        public string TeacherCode { get; set; }
        public string TeacherName { get; set; }
        public string Gender { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Age { get; set; }
        public Nullable<decimal> CnicNo { get; set; }
        public Nullable<decimal> ContactNo { get; set; }
        public string AcademicQualification { get; set; }
        public string ProfessionalQualification { get; set; }
        public string TrainedByPef { get; set; }
        public string NtsCertification_Pass_Fail { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<System.DateTime> DateOfAppointment { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> AnyTraining { get; set; }
    
        public virtual Entity Entity1 { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual Section Section1 { get; set; }
        public virtual Survey Survey { get; set; }
        public virtual TeacherCode TeacherCode1 { get; set; }
    }
}
